# Generated by Django 2.2.5 on 2019-09-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantitu',
            new_name='quantity',
        ),
    ]
